name: checks
on: [pull_request]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: asdf-vm/actions/install@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v5
        with:
          cache: pnpm
      - uses: ocaml/setup-ocaml@v3
        with:
          dune-cache: true
          ocaml-compiler: 5
          opam-disable-sandboxing: true
      - run: opam install . --deps-only --with-test
      - run: opam exec -- opam-dune-lint
      - run: pnpm install --frozen-lockfile
      - run: pnpm run format:check
      - run: opam check-npm-deps
      - run: opam exec -- dune build @fmt
      - run: opam exec -- dune build
      - run: pnpm test
      - run: pnpm run build
      - run: pnpm run check-size-limits
