name: checks
on:
  push:
    branches:
      - '**'
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: asdf-vm/actions/install@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v5
        with:
          cache: pnpm
      - uses: actions/cache@v4
        id: cache-opam
        with:
          key: |
            opam-cache-v1-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('violette.opam') }}
          restore-keys: |
            opam-cache-v1-${{ runner.os }}-${{ runner.arch }}-
          path: |
            ~/.opam
            _opam
      - run: opam init --auto-setup --bare --disable-sandboxing && opam switch create --yes --deps-only --with-dev-setup .
        if: ${{ steps.cache-opam.outputs.cache-hit == '' }}
      - run: opam install --deps-only --with-dev-setup .
        if: ${{ steps.cache-opam.outputs.cache-hit != '' }}
      - run: opam exec -- opam-dune-lint
      - run: pnpm install --frozen-lockfile
      - run: pnpm run format:check
      - run: opam check-npm-deps
      - run: opam exec -- dune build @fmt
      - run: opam exec -- dune build
      - run: pnpm test
      - run: pnpm run build
      - run: pnpm run check-size-limits
