name: deploy
on:
  push:
    branches:
      - '**'
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true
jobs:
  deploy:
    environment:
      name: cloudflare
      url: ${{ steps.wrangler.outputs.deployment-url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: asdf-vm/actions/install@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v5
        with:
          cache: pnpm
      - uses: actions/cache@v4
        id: cache-opam
        with:
          key: |
            opam-cache-v1-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('violette.opam') }}
          restore-keys: |
            opam-cache-v1-${{ runner.os }}-${{ runner.arch }}-
          path: |
            ~/.opam
            _opam
      - run: opam init --auto-setup --bare --disable-sandboxing && opam switch create --yes --deps-only --with-dev-setup .
        if: ${{ steps.cache-opam.outputs.cache-hit == '' }}
      - run: opam install --deps-only --with-dev-setup .
        if: ${{ steps.cache-opam.outputs.cache-hit != '' }}
      - run: pnpm install --frozen-lockfile
      - run: opam exec -- dune build
      - run: pnpm run build
      - uses: cloudflare/wrangler-action@v3
        id: wrangler
        with:
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
